=== hethon/ingen/schema/manifest.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "app_name": {
      "type": "string",
      "minLength": 1
    },
    "app_version": {
      "type": "string",
      "minLength": 1
    },
    "base_urls": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "hosting": {
      "type": "object",
      "properties": {
        "github": {
          "type": "object",
          "properties": {
            "artifact_download_path": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "artifact_download_path"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "github"
      ],
      "additionalProperties": false
    },
    "install_success_msg": {
      "type": "string",
      "minLength": 1
    },
    "install_paths": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "bin_aliases": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "owner": {
      "type": "string",
      "minLength": 1
    },
    "repo": {
      "type": "string",
      "minLength": 1
    },
    "tag": {
      "type": "string",
      "minLength": 1
    },
    "windows_archive": {
      "type": "object",
      "properties": {
        "style": {
          "type": "string",
          "enum": [
            ".tar.gz",
            ".tar.xz",
            ".tar.zst",
            ".zip"
          ]
        },
        "layout": {
          "type": "string",
          "enum": [
            "flat",
            "wrapped"
          ]
        }
      },
      "required": [
        "style",
        "layout"
      ],
      "additionalProperties": false
    },
    "unix_archive": {
      "type": "object",
      "properties": {
        "style": {
          "type": "string",
          "enum": [
            ".tar.gz",
            ".tar.xz",
            ".tar.zst",
            ".zip"
          ]
        },
        "layout": {
          "type": "string",
          "enum": [
            "flat",
            "wrapped"
          ]
        }
      },
      "required": [
        "style",
        "layout"
      ],
      "additionalProperties": false
    },
    "executables": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "cdylibs": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "cstaticlibs": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "checksum_style": {
      "type": "string",
      "enum": [
        "sha256",
        "sha512",
        "sha3-256",
        "sha3-512",
        "blake2s",
        "blake2b"
      ]
    },
    "min_glibc_version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+$"
    },
    "platform_support": {
      "type": "object",
      "properties": {
        "archives": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "minLength": 1
              },
              "target_triple": {
                "type": "string",
                "pattern": "^[a-z0-9_]+(-[a-z0-9_.]+){2,4}$"
              },
              "checksum": {
                "type": "string",
                "minLength": 1
              },
              "executables": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "cdylibs": {
                "type": "array",
                "items": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "cstaticlibs": {
                "type": "array",
                "items": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "zip_style": {
                "type": "string",
                "enum": [
                  ".tar.gz",
                  ".tar.xz",
                  ".tar.zst",
                  ".zip"
                ]
              },
              "checksum_style": {
                "type": "string",
                "enum": [
                  "sha256",
                  "sha512",
                  "sha3-256",
                  "sha3-512",
                  "blake2s",
                  "blake2b"
                ]
              },
              "min_glibc_version": {
                "type": "string",
                "pattern": "^\\d+\\.\\d+$"
              },
              "layout": {
                "type": "string",
                "enum": [
                  "flat",
                  "wrapped"
                ]
              }
            },
            "required": [
              "id",
              "target_triple"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "archives"
      ],
      "additionalProperties": false
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "app_name",
    "app_version",
    "base_urls",
    "hosting",
    "install_success_msg",
    "install_paths",
    "bin_aliases",
    "owner",
    "repo",
    "tag",
    "windows_archive",
    "unix_archive",
    "executables",
    "cdylibs",
    "cstaticlibs",
    "checksum_style",
    "platform_support"
  ],
  "additionalProperties": false
}

=== hethon/ingen/src/example.manifest.json
{
  "app_name": "my-app",
  "app_version": "0.1.0",
  "owner": "my-org",
  "repo": "my-app",
  "tag": "v{app_version}",
  "base_urls": ["https://github.com/{owner}/{repo}/releases/download/{tag}"],
  "hosting": {
    "github": {
      "artifact_download_path": "/{owner}/{repo}/releases/download/{tag}"
    }
  },
  "windows_archive": {
    "style": ".zip",
    "layout": "flat"
  },
  "unix_archive": {
    "style": ".tar.gz",
    "layout": "wrapped"
  },
  "executables": ["my-app"],
  "cdylibs": [],
  "cstaticlibs": [],
  "min_glibc_version": "2.17",
  "checksum_style": "sha256",
  "bin_aliases": {},
  "install_paths": ["~/.local/bin"],
  "install_success_msg": "my-app was successfully installed!",
  "platform_support": {
    "archives": [
      {
        "id": "my-app-{app_version}-x86_64-unknown-linux-gnu.tar.gz",
        "target_triple": "x86_64-unknown-linux-gnu",
        "checksum": "0000000000000000000000000000000000000000000000000000000000000000"
      }
    ]
  }
}

=== hethon/ingen/examples/tectonic/installer.manifest.json
{
  "$schema": "../../schema/manifest.schema.json",

  "app_name": "tectonic",
  "owner": "tectonic-typesetting",
  "repo": "tectonic",
  "app_version": "0.17.0",
  "tag": "tectonic@{app_version}",
  "base_urls": ["https://github.com/{owner}/{repo}/releases/download/{tag}"],
  "hosting": {
    "github": {
      "artifact_download_path": "/{owner}/{repo}/releases/download/{tag}"
    }
  },
  "install_paths": ["$XDG_BIN_HOME/", "$XDG_DATA_HOME/../bin", "~/.local/bin"],
  "install_success_msg": "Tectonic (and the Nextonic V2 CLI) installed successfully!",
  "bin_aliases": { "tectonic": ["nextonic"] },
  "windows_archive": {
    "style": ".zip",
    "layout": "flat"
  },
  "unix_archive": {
    "style": ".tar.gz",
    "layout": "flat"
  },
  "executables": ["tectonic"],
  "cdylibs": [],
  "cstaticlibs": [],
  "checksum_style": "sha256",
  "platform_support": {
    "archives": [
      {
        "id": "tectonic-{app_version}-aarch64-apple-darwin.tar.gz",
        "target_triple": "aarch64-apple-darwin",
        "checksum": "a3f1cac7c5678f01661a92212f58480ae3b0634115d880dbc59e2953ded45667"
      },
      {
        "id": "tectonic-{app_version}-aarch64-unknown-linux-musl.tar.gz",
        "target_triple": "aarch64-unknown-linux-musl",
        "checksum": "b10954a95404f3ab2328d2fa59a5ebab8e657f893fab096f98be8db7c0c979b8"
      },
      {
        "id": "tectonic-{app_version}-arm-unknown-linux-musleabihf.tar.gz",
        "target_triple": "arm-unknown-linux-musleabihf",
        "checksum": "882f5213599931992dfb9f7e1157d3015fd9abd505c68c693b3d6dc20967f7eb"
      },
      {
        "id": "tectonic-{app_version}-i686-unknown-linux-gnu.tar.gz",
        "target_triple": "i686-unknown-linux-gnu",
        "checksum": "f4c887268be8ce443de7b4ccb67d6978fe40113ae8872310957693bb80d07ff4"
      },
      {
        "id": "tectonic-{app_version}-x86_64-apple-darwin.tar.gz",
        "target_triple": "x86_64-apple-darwin",
        "checksum": "7c90ef5b6ddb1eb1937e4337add5237b79338e4b9676459fa91187d24d6cdf80"
      },
      {
        "id": "tectonic-{app_version}-x86_64-pc-windows-gnu.zip",
        "target_triple": "x86_64-pc-windows-gnu",
        "checksum": "77a0ebba1cc54f6145dbc27377e253c9fffa07eab7c368ff9ef30c2d05557365"
      },
      {
        "id": "tectonic-{app_version}-x86_64-pc-windows-msvc.zip",
        "target_triple": "x86_64-pc-windows-msvc",
        "checksum": "f61ce51f0b0ade1015b7de7ef368541c5424e9756ecbd0d7af97d6d48030845f"
      },
      {
        "id": "tectonic-{app_version}-x86_64-unknown-linux-gnu.tar.gz",
        "target_triple": "x86_64-unknown-linux-gnu",
        "checksum": "1a715688baf591e650c8aeb160ae934e181685eecbb38b317de30b269ac5d606"
      },
      {
        "id": "tectonic-{app_version}-x86_64-unknown-linux-musl.tar.gz",
        "target_triple": "x86_64-unknown-linux-musl",
        "checksum": "8533d07f9ccbd7a65824b9e0459041bca34af1eb33daba48f59215593753a3b7"
      }
    ]
  }
}
